#  Indexing and Selection

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("ball_by_ball_ipl.csv")
df

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,0,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad,...,Chennai Super Kings,0,4,0,1,0,NaN,NaN,4,1
1,1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239688,239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan,...,Sunrisers Hyderabad,1,16,31,9,29,NaN,NaN,2,1
239689,239689,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,2,YK Pathan,...,Sunrisers Hyderabad,1,22,31,10,29,NaN,NaN,6,1
239690,239690,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,3,YK Pathan,...,Sunrisers Hyderabad,1,26,31,11,29,NaN,NaN,4,1
239691,239691,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,4,YK Pathan,...,Sunrisers Hyderabad,1,27,31,12,29,NaN,NaN,1,1
239692,239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson,...,Sunrisers Hyderabad,1,32,27,30,12,NaN,NaN,1,1

In [5]:
df.info

<bound method DataFrame.info of         Unnamed: 0  Match ID        Date                               Venue  \
0                0   1359507  2023-04-23                        Eden Gardens
1                1   1359507  2023-04-23                        Eden Gardens
2                2   1359507  2023-04-23                        Eden Gardens
3                3   1359507  2023-04-23                        Eden Gardens
4                4   1359507  2023-04-23                        Eden Gardens
...            ...       ...         ...                                 ...
239688      239688   1136596  2018-05-05  Rajiv Gandhi International Stadium
239689      239689   1136596  2018-05-05  Rajiv Gandhi International Stadium
239690      239690   1136596  2018-05-05  Rajiv Gandhi International Stadium
239691      239691   1136596  2018-05-05  Rajiv Gandhi International Stadium
239692      239692   1136596  2018-05-05  Rajiv Gandhi International Stadium

                  Bat First             Bat Second  Innings  Over  Ball  \
0       Chennai Super Kings  Kolkata Knight Riders        1     1     1
1       Chennai Super Kings  Kolkata Knight Riders        1     1     2
2       Chennai Super Kings  Kolkata Knight Riders        1     1     3
3       Chennai Super Kings  Kolkata Knight Riders        1     1     4
4       Chennai Super Kings  Kolkata Knight Riders        1     1     5
...                     ...                    ...      ...   ...   ...
239688     Delhi Daredevils    Sunrisers Hyderabad        2    20     1
239689     Delhi Daredevils    Sunrisers Hyderabad        2    20     2
239690     Delhi Daredevils    Sunrisers Hyderabad        2    20     3
239691     Delhi Daredevils    Sunrisers Hyderabad        2    20     4
239692     Delhi Daredevils    Sunrisers Hyderabad        2    20     5

               Batter  ...               Winner Chased Successfully  \
0          RD Gaikwad  ...  Chennai Super Kings                   0
1          RD Gaikwad  ...  Chennai Super Kings                   0
2          RD Gaikwad  ...  Chennai Super Kings                   0
3          RD Gaikwad  ...  Chennai Super Kings                   0
4          RD Gaikwad  ...  Chennai Super Kings                   0
...               ...  ...                  ...                 ...
239688      YK Pathan  ...  Sunrisers Hyderabad                   1
239689      YK Pathan  ...  Sunrisers Hyderabad                   1
239690      YK Pathan  ...  Sunrisers Hyderabad                   1
239691      YK Pathan  ...  Sunrisers Hyderabad                   1
239692  KS Williamson  ...  Sunrisers Hyderabad                   1

        Total Batter Runs  Total Non Striker Runs  Batter Balls Faced  \
0                       4                       0                   1
1                       4                       0                   2
2                       4                       0                   3
3                       4                       0                   4
4                       5                       0                   5
...                   ...                     ...                 ...
239688                 16                      31                   9
239689                 22                      31                  10
239690                 26                      31                  11
239691                 27                      31                  12
239692                 32                      27                  30

        Non Striker Balls Faced Player Out Runs  Player Out Balls Faced  \
0                             0             NaN                     NaN
1                             0             NaN                     NaN
2                             0             NaN                     NaN
3                             0             NaN                     NaN
4                             0             NaN                     NaN
...                         ...             ...                     ...
239688                       29             NaN                     NaN
239689                       29             NaN                     NaN
239690                       29             NaN                     NaN
239691                       29             NaN                     NaN
239692                       12             NaN                     NaN

       Bowler Runs Conceded Valid Ball
0                         4          1
1                         0          1
2                         0          1
3                         0          1
4                         1          1
...                     ...        ...
239688                    2          1
239689                    6          1
239690                    4          1
239691                    1          1
239692                    1          1

[239693 rows x 35 columns]>

# indexing

## Types of indexing

1. Basic indexing ([] Operator)
2. Label-based indexing(loc)
3. Integer-based indexing(iloc)

# Indexing Operator[]:-
The [] operator is the simplest way to access data in a DataFrame. 
it is mainly used for column selection.
    1. selecting a single Column.
    2. selecting Multiple Column.

In [6]:
df['Batter']

0            RD Gaikwad
1            RD Gaikwad
2            RD Gaikwad
3            RD Gaikwad
4            RD Gaikwad
              ...
239688        YK Pathan
239689        YK Pathan
239690        YK Pathan
239691        YK Pathan
239692    KS Williamson
Name: Batter, Length: 239693, dtype: object

In [7]:
df[['Batter','Winner']]

               Batter               Winner
0          RD Gaikwad  Chennai Super Kings
1          RD Gaikwad  Chennai Super Kings
2          RD Gaikwad  Chennai Super Kings
3          RD Gaikwad  Chennai Super Kings
4          RD Gaikwad  Chennai Super Kings
...               ...                  ...
239688      YK Pathan  Sunrisers Hyderabad
239689      YK Pathan  Sunrisers Hyderabad
239690      YK Pathan  Sunrisers Hyderabad
239691      YK Pathan  Sunrisers Hyderabad
239692  KS Williamson  Sunrisers Hyderabad

[239693 rows x 2 columns]

# .loc[] - Label based Selection

# .loc[] is used to select data by labels(row/column names).
# It allows slicing and boolean conditions

In [8]:
df.loc[[239688,239692]]

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
239688,239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan,...,Sunrisers Hyderabad,1,16,31,9,29,NaN,NaN,2,1
239692,239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson,...,Sunrisers Hyderabad,1,32,27,30,12,NaN,NaN,1,1

In [9]:
df.loc[:,'Over']

0          1
1          1
2          1
3          1
4          1
          ..
239688    20
239689    20
239690    20
239691    20
239692    20
Name: Over, Length: 239693, dtype: int64

In [10]:
df.loc[:,['Bat First','Venue']]

                  Bat First                               Venue
0       Chennai Super Kings                        Eden Gardens
1       Chennai Super Kings                        Eden Gardens
2       Chennai Super Kings                        Eden Gardens
3       Chennai Super Kings                        Eden Gardens
4       Chennai Super Kings                        Eden Gardens
...                     ...                                 ...
239688     Delhi Daredevils  Rajiv Gandhi International Stadium
239689     Delhi Daredevils  Rajiv Gandhi International Stadium
239690     Delhi Daredevils  Rajiv Gandhi International Stadium
239691     Delhi Daredevils  Rajiv Gandhi International Stadium
239692     Delhi Daredevils  Rajiv Gandhi International Stadium

[239693 rows x 2 columns]

In [11]:
df.loc[:,'Match ID':'Batter']

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter
0,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad
1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad
2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad
3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad
4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad
...,...,...,...,...,...,...,...,...,...
239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan
239689,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,2,YK Pathan
239690,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,3,YK Pathan
239691,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,4,YK Pathan
239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson

In [12]:
# .loc[]- Conditional Row Selection
df.loc[df['Method'] == 'lbw']

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
167,167,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,8,1,VR Iyer,...,Chennai Super Kings,0,0,22,0,18,20.0,20.0,0,1
234,234,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,18,3,D Wiese,...,Chennai Super Kings,0,0,44,0,27,1.0,2.0,0,1
305,305,392217,2009-05-09,De Beers Diamond Oval,Rajasthan Royals,Chennai Super Kings,1,9,5,SA Asnodkar,...,Chennai Super Kings,1,0,25,0,26,26.0,26.0,0,1
392,392,392217,2009-05-09,De Beers Diamond Oval,Rajasthan Royals,Chennai Super Kings,2,3,6,M Vijay,...,Chennai Super Kings,1,0,8,0,6,10.0,12.0,0,1
631,631,1254112,2021-10-02,Sharjah Cricket Stadium,Mumbai Indians,Delhi Capitals,2,3,4,PP Shaw,...,Delhi Capitals,1,0,1,0,2,6.0,7.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238611,238611,419122,2010-03-22,Brabourne Stadium,Kolkata Knight Riders,Mumbai Indians,1,20,6,CH Gayle,...,Mumbai Indians,1,0,3,0,3,75.0,62.0,0,1
238710,238710,419122,2010-03-22,Brabourne Stadium,Kolkata Knight Riders,Mumbai Indians,2,16,5,KA Pollard,...,Mumbai Indians,1,0,65,0,44,7.0,7.0,0,1
238989,238989,1178396,2019-04-07,Sawai Mansingh Stadium,Rajasthan Royals,Kolkata Knight Riders,1,2,1,AM Rahane,...,Kolkata Knight Riders,1,0,0,0,0,5.0,7.0,0,1
239438,239438,598012,2013-04-13,MA Chidambaram Stadium,Royal Challengers Bangalore,Chennai Super Kings,2,19,4,DJ Bravo,...,Chennai Super Kings,1,0,26,0,16,8.0,4.0,0,1
239549,239549,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,1,17,5,RR Pant,...,Sunrisers Hyderabad,1,0,1,0,3,18.0,20.0,0,1

# .iloc[]- Position based indexing

.iloc[] is used to select data by integer index position.
-> Rows and columns are selected baased on their numberical position in the Dataframe.
-> follows zero-based indexing.1

In [13]:
# .iloc[] -- single row selection
df.iloc[2]

Unnamed: 0                                     2
Match ID                                 1359507
Date                                  2023-04-23
Venue                               Eden Gardens
Bat First                    Chennai Super Kings
Bat Second                 Kolkata Knight Riders
Innings                                        1
Over                                           1
Ball                                           3
Batter                                RD Gaikwad
Non Striker                            DP Conway
Bowler                                  UT Yadav
Batter Runs                                    0
Extra Runs                                     0
Runs From Ball                                 0
Ball Rebowled                                  0
Extra Type                                    []
Wicket                                         0
Method                                       NaN
Player Out                                   NaN
Innings Runs                                   4
Innings Wickets                                0
Target Score                                 236
Runs to Get                                  NaN
Balls Remaining                              117
Winner                       Chennai Super Kings
Chased Successfully                            0
Total Batter Runs                              4
Total Non Striker Runs                         0
Batter Balls Faced                             3
Non Striker Balls Faced                        0
Player Out Runs                              NaN
Player Out Balls Faced                       NaN
Bowler Runs Conceded                           0
Valid Ball                                     1
Name: 2, dtype: object

In [14]:
df.iloc[[2,3,4,5]] # multi label selection

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
2,2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1
5,5,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,6,DP Conway,...,Chennai Super Kings,0,0,5,1,5,NaN,NaN,0,1

In [15]:
# .iloc -- column selection
df.iloc[:,2:5]

              Date                               Venue            Bat First
0       2023-04-23                        Eden Gardens  Chennai Super Kings
1       2023-04-23                        Eden Gardens  Chennai Super Kings
2       2023-04-23                        Eden Gardens  Chennai Super Kings
3       2023-04-23                        Eden Gardens  Chennai Super Kings
4       2023-04-23                        Eden Gardens  Chennai Super Kings
...            ...                                 ...                  ...
239688  2018-05-05  Rajiv Gandhi International Stadium     Delhi Daredevils
239689  2018-05-05  Rajiv Gandhi International Stadium     Delhi Daredevils
239690  2018-05-05  Rajiv Gandhi International Stadium     Delhi Daredevils
239691  2018-05-05  Rajiv Gandhi International Stadium     Delhi Daredevils
239692  2018-05-05  Rajiv Gandhi International Stadium     Delhi Daredevils

[239693 rows x 3 columns]

In [16]:
# row slicing
df.iloc[1:3]

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
1,1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1

In [17]:
# .iloc[]-- Row and column selection
df.iloc[1:3,0:3]

   Unnamed: 0  Match ID        Date
1           1   1359507  2023-04-23
2           2   1359507  2023-04-23

In [ ]:

.iloc[] VS .iloc[]

Feature

Indexing Type

Slicing Behavior

Conditional Selection

Use Cases

                    .Joc[] (Label-based)
                    
                    Uses LABELS for indexing
                    
                    Inclusive of both start and end position
                    
                    Can use boolean conditions directly
                    
                    Use when selecting by label

                                                            .iloc[] (Position-based)
                                                            
                                                            Uses INTEGER POSITIONS
                                                            
                                                            Excludes the end position
                                                            
                                                            Cannot use boolean conditions
                                                            
                                                            Use when selecting by position

# Aggregation and Grouping

# groupby()

# groupby()
-> The groupby() function in pandas is used to group similar data together
and platform calculations on each group.
-> It helps in organizating and analyzing large data sets by breaking them into 
smaller part based on a comma feacture.
-> Once we have grouped the data,we often need to perform calculation on each group
this is where aggregation comes in.

# Aggregation

-> Aggregation is the process of applying summery statistics or mathmatical 
functions to grouped data.

-> 
sum()
mean()
count()
min()
max()

In [19]:
df['Batter Runs'].mean()

np.float64(1.2523728269077528)

In [20]:
df['Batter Runs'].sum()

np.int64(300185)

In [21]:
df['Batter Runs'].count()

np.int64(239693)

In [22]:
df['Batter Runs'].min()

0

In [23]:
df['Batter Runs'].max()

6